import { RootPage, generatePageMetadata } from '@payloadcms/next/views'
// This file is automatically generated by Payload.
// It is used to map custom components to the admin UI.
// For now, we export an empty object.
export const importMap = {}
